# Generated by Django 3.0.5 on 2020-04-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_commentreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='post',
        ),
    ]
