# Generated by Django 2.0.3 on 2020-02-28 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
