# Generated by Django 3.0.4 on 2020-04-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200410_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profile/avatar.png', upload_to='images/profile'),
        ),
    ]
