# Generated by Django 3.0.4 on 2020-04-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200410_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(blank=True, default='images/cover/background.png', upload_to='images/cover'),
        ),
    ]
