# Generated by Django 3.0.4 on 2020-04-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(blank=True, default='images/cover/background.jpg', upload_to='images/cover'),
        ),
    ]
