# Generated by Django 3.0.4 on 2020-04-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200411_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(unique=True, verbose_name='username'),
        ),
    ]
