# Generated by Django 3.0.4 on 2020-04-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200411_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='slug',
        ),
    ]
