# Generated by Django 3.0.4 on 2020-04-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200411_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_admin',
            field=models.CharField(default='<i class="fas fa-award" style="font-size:20px;color:rgb(46, 218, 12);"></i>', max_length=255),
        ),
    ]
