# Generated by Django 3.0.4 on 2020-04-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_admin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
