# Generated by Django 3.0.5 on 2020-05-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_delete_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='slug',
            new_name='username',
        ),
    ]
