"""
Django settings for drex project.

Generated by 'django-admin startproject' using Django 1.11.28.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_ROOT = os.path.abspath(os.path.join(os.path.split(__file__)[0], '..'))

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5=vef^nwv)t)s)7y++xw7zv%1%k__)l&%h1x7)1a(m$tl1$a+f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'courses.apps.CoursesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'posts.apps.PostsConfig',
    'actions.apps.ActionsConfig',
    'custom.apps.CustomConfig',
    'chat.apps.ChatConfig',
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
    #third party apps
    'rest_framework',
    'webpush',
    'channels',

    #Own apps
    'canvas',
    'PIL',
    'crispy_forms',
    'sorl.thumbnail',
    #'chat',
    #'stream_twitter'
    
]
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BMzQ0kBTQLwwdqHOzM18SX_tW_1V0hN4nqoMV5MzQvEAT0pk7fs1dAiI5U7lDpCnLCRelINZs2cisdP-P3EtjbM",
    "VAPID_PRIVATE_KEY":"NPpD17YF6uixngSHm0vomA3QOkerMVoz91UBmR46IBc",
    "VAPID_ADMIN_EMAIL": "joshua.franklin.codes@gmail.com"
}

CRISPY_TEMPLATE_PACK = "bootstrap4"

# Email Confirmation Setup
EMAIL_USE_TLS = True
EMAIL_HOST = 'send.one.com'
EMAIL_HOST_USER = 'info@ecoparty.org'
EMAIL_HOST_PASSWORD = '2lt@speeDjoy'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = 'DREXNET Team <noreply@ecoparty.org>'

STREAM_API_KEY = 'z8ebq62q8k6j'
STREAM_API_SECRET = 'bpde7nnkuscmd3gygj9vr6gg95fdf54wwdk9evfu48eyuh3y5fdf8x7ejqwydh7e'

STREAM_NEWS_FEEDS = dict(timeline='timeline')



AUTH_USER_MODEL = 'users.User'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'users.middleware.ActiveUserMiddleware',
]

ROOT_URLCONF = 'drex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'drex.wsgi.application'
# Channels
ASGI_APPLICATION = 'drex.routing.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db2.sqlite3'),
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'drexnet_db',
#         'USER': 'drex_admin',
#         'PASSWORD': 'password',
#         'HOST': 'localhost',
#         'PORT': '',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
            'LOCATION': '127.0.0.1:11211',              
        }
    }

USER_ONLINE_TIMEOUT = 300
USER_LASTSEEN_TIMEOUT = 60 * 60 * 24 * 7

CART_SESSION_ID = 'cart'

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
LOGIN_URL = '/user'

REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0

CHANNEL_LAYERS = {
    "default":{
        "BACKEND":"channels_redis.core.RedisChannelLayer",
        "CONFIG":{
            "hosts":[('localhost', 6379)],
        }
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES':(
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES':(
        # 'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}